### ISSUE TITLE
SASS version would be nice

### ISSUE THREAD

**Issue by iamstuartwilson** [leejordan/reflex#11]

**Comment by iamstuartwilson** [comment]
@leejordan, don't worry I'm on it!

**Comment by leejordan** [comment]
:+1:

**Comment by kerns** [comment]
Look forward to seeing it in Sass (well, ...scss).

**Comment by MarcelHekkert** [comment]
+1 Would be a great thing to have!

**Comment by leejordan** [comment]
@iamstuartwilson provided a solution to generate a .scss file which can be imported into sass projects. It's not a SASS version per se but it's a start.

https://github.com/leejordan/reflex/pull/16
