### ISSUE TITLE
Abstract Media Queries and Make Them Easily Configurable

### ISSUE THREAD

**Issue by kerns** [leejordan/reflex#19]
Thrilled to see the scss version, thanks for that.

Now I would just like to see a media query setup that was less opinionated and more configurable. I really love the way gridlex tackles it.

[https://github.com/devlint/gridlex/blob/master/src/gridlex-vars.scss](https://github.com/devlint/gridlex/blob/master/src/gridlex-vars.scss)

Of course I can go in and manually change Reflex to match our already established media queries and breakpoints – but breakpoints change in the development and testing – keeping them updated using the current approach would be a headache. Also, upgrading to future versions of Reflex is made more difficult.

**Comment by leejordan** [comment]
If you use the LESS files you can change these breakpoints via variables but I haven't set up a "proper" SASS version yet. One day I hope to do so because I'm using SASS more and more as time goes by.

**Comment by leejordan** [comment]
there is a proper scss build now so you can incorporate it into your scss workflow and amend the variables including breakpoints to your desired values.
