### ISSUE TITLE
No inline-block with IE <=10

### ISSUE THREAD

**Issue by pwFoo** [leejordan/reflex#24]
Hello,

I tested your reflex demo with IE-Tester, but no inline-blocks with IE <=10? So just the flexbox native support for modern browsers?
What's about columns with IE 8/9 or 10?

Regards

**Comment by leeoniya** [comment]
wonder if it's related to https://github.com/leejordan/reflex/issues/23

**Comment by leejordan** [comment]
Can you link me to the tool you are using for testing? I know it works on ie <10 because it's used in production on many sites and I tested it myself in vms and on browserstack.

**Comment by pwFoo** [comment]
[IE-tester](http://www.my-debugbar.com/wiki/IETester/HomePage) which I also used in the past and [IECollection](http://utilu.com/IECollection/#download) to verify it again.
WinXP / Win7 VM. Also native IE inside the VM.

**Comment by leejordan** [comment]
@pwFoo can you share your markup please? At least just the grid parts.

**Comment by pwFoo** [comment]
Hi @leejordan 
I used your demo ;) It was a first test before I build my own layout with reflex (if it works).
http://leejordan.github.io/reflex/docs/demo.html

**Comment by leejordan** [comment]
I am on a mac and it looks like neither of those applications will work on mac. Can you post a screenshot perhaps?

I test on a vm and browserstack and on the demo page I can see that I still get an intact inline-block grid on non flexbox browsers although some of the features do not have fallbacks. For example you won't get same height divs, and auto width columns do not work but for the most part, layout is almost exactly the same.

If you look at the main documentation page which only contains the grid and nothing else you should see an intact grid all the way back to ie7: http://leejordan.github.io/reflex/docs/index.html (apart from the auto columns which don't have a fallback)

**Comment by pwFoo** [comment]
Demo grid (http://leejordan.github.io/reflex/docs/index.html) works with Win7 IE-Tester with all the browsers! Don't know why other demo doesn't worked... Thanks.
I'll do some more testing in the next time.

It was important to see it basically works with IE8+ as grid (with inline block fallback).
Maybe I can move to reflex soon :)

**Comment by leejordan** [comment]
Ok so what has happened here is when adding some of the demos I have added on some extra css on top of the core grid which doesn't fall back so well. I will take some time to sort this out because it makes me look bad :)
