### ISSUE TITLE
Box model defined globally with wildcard

### ISSUE THREAD

**Issue by frabonomi** [leejordan/reflex#25]
Hey @leejordan I noticed [you set](https://github.com/leejordan/reflex/blob/master/scss/reflex/_grid.scss#L6) the `box-sizing: border-box` declaration for all elements with the `*` selector. I'm wondering if that should be defined only on the elements of the grid. 
Is there a reason to set it to all elements?

**Comment by leejordan** [comment]
This is my personal preference. I always want to use `box-sizing: border-box` myself. Is it causing you problems?

**Comment by frabonomi** [comment]
I'm also a big fan of setting `box-sizing` to `border-box` as I consider it a best practice, but I'm working on a project with a large codebase that unfortunately has a lot of components relying on the fact that the default value is `content-box`.
Would you ever consider to make the rule specific to the grid and its children?

**Comment by leejordan** [comment]
This is a fair point actually. I will consider changing this in the next version. In the meantime you could change this yourself fairly easily right? I guess it depends on how you are loading the scss/less/css.

**Comment by frabonomi** [comment]
Yes, in the meanwhile I can definitely do that. Thank you!

**Comment by CydGoblin** [comment]
If it's a best practice to have `box-sizing: border-box` then it would be better to keep it like that and customize it when needed.

**Comment by leejordan** [comment]
I don't see the harm in moving the box-sizing wildcard selector inside the grid as it ensures the grid's css is all self-contained without affecting anything outside the grid itself.

However, as most sites will already be using `box-sizing: border-box;` it does worry me that we'd have redundant properties inside this library but I feel like this is the best solution for the reason outlined above.

**Comment by leejordan** [comment]
This is changed in commit https://github.com/leejordan/reflex/commit/5a4375130ce9adba46b16d96561b9313a1479870 to master and I will release a new version soon

**Comment by frabonomi** [comment]
Thanks @leejordan!
