### ISSUE TITLE
text-align-last causes problems in IE11

### ISSUE THREAD

**Issue by gilluminate** [leejordan/reflex#26]
`test-align-last` is inherited down through all of the elements within, so even though IE11 does support flexbox, it does support that property. That hack causes the need to supplement every usage of `text-align: right` to also contain `text-align-last: right` and so on or it is broken which is a major pain throughout an entire app.

**Comment by gilluminate** [comment]
Actually, I was able to track it down a bit further. It appears that IE11 is not respecting 'start' or 'initial' as valid values and therefore 'left' is the only one being applied. So every time we use a text-align other than what has been set using the `__justify--x` modifier, we also have to apply text-align-last.

Is 'text-align-last' the only way to address the last row?

**Comment by leejordan** [comment]
I merged your PR and added a new commit to duplicate it in LESS

**Comment by leejordan** [comment]
Thanks for your help
