### ISSUE TITLE
package.json should have a "main"

### ISSUE THREAD

**Issue by jreichenberg** [leejordan/reflex#31]
package.json is missing a "main" field.  bower.json has

```
"main": "css/reflex.css",
```

What are your thoughts about making package.json have the same?  I'm using https://www.npmjs.com/package/resolve to resolve the location of the installed package and it relies on having a "main" field that points to a file (or index.js).

**Comment by leejordan** [comment]
Sure, I will add this. At the very least just for consistency between npm and bower :)

**Comment by leejordan** [comment]
Fixed by this commit to master https://github.com/leejordan/reflex/commit/b1955f9891128fac18af72878125df2623eb7014

New release coming later with some other changes.
