### ISSUE TITLE
Allow setting vertical padding separately

### ISSUE THREAD

**Issue by Kaivosukeltaja** [leejordan/reflex#34]
I really like Reflex but have some issues with `$reflex-grid-spacing` adding vertical padding as well. I'm trying to position items accurately but having unwanted padding appear at the top and bottom of grid items is making it more difficult than necessary.

Could we have a `$reflex-grid-spacing-vertical` setting that would default to `$reflex-grid-spacing`?

**Comment by andreasisaak** [comment]
Yeah this is very annoying. I seperate the spacing into grid and cell spacing to avoid vertical padding. 

https://github.com/LOUISINTERNET/reflex/commit/570255e0c1f110baa4bdbeec46c14fa6117949cd

If you desired @leejordan, i will create a pull request.

**Comment by leejordan** [comment]
This is a fine suggestion and I will be implementing it shortly. Thanks!
