### ISSUE TITLE
Change project name

### ISSUE THREAD

**Issue by bbenezech** [leejordan/reflex#37]
Hard to find/noise on Google, Twitter or Github. 

I just counted, there is exactly one million and one project named Reflex on the whole internet, not counting the dark web (too scared to check). 

You should change to yafl, encoreflex, suchflex, flexontheDOM, bootflexstrap, flexfoo or xelfer. 

Also you need a cool logo, otherwise people won't know for sure you created the best flex grid out there. 

I am not a designer but you probably need some cute animal wearing a too cool for school T-Shirt.

**Comment by iamstuartwilson** [comment]
@bbenezech @leejordan I'm not a designer either, but can I present to you the Reflex Sloth?

![image](https://cloud.githubusercontent.com/assets/3594817/20557336/fb8591d2-b162-11e6-93bb-8f9ac37fd425.png)

Everyone knows that sloths are renouned for their excellent reflexes, not to mention their ability to always centre themselves vertically.

Please vote with reactions:
👍  YES
👎  NO

Thx

**Comment by marzepani** [comment]
@leejordan I really like the idea to polish your awesome work.

I recommend something like **Flexagon** or **Flexatron**. I kinda think a Retro-Sci-Fi style fits perfectly to a modern/futuristic approach with legacy fallback.
Flexagon hasn't exactly any connection to this, I think, but it would certainly make it easy to find a logo. ;-)

(I would be able to help with the logo, if there is any interest.)

**Comment by leejordan** [comment]
Well this is certainly some food for thought :)
