### ISSUE TITLE
grid__col-auto would be nice

### ISSUE THREAD

**Issue by argyleink** [leejordan/reflex#4]
1 flexbox feature I can't seem to figure out with your lib is an auto column option.

**Comment by leejordan** [comment]
I've added this to this branch: https://github.com/leejordan/reflex/tree/autoCols

Can you confirm it's what you were expecting. The only issue with auto columns is that it doesn't fully work in the inline-block fallback:

Flexbox:

![screen shot 2015-08-18 at 16 35 22](https://cloud.githubusercontent.com/assets/713293/9334522/2ec31334-45c7-11e5-97cd-4302cc4d0db7.png)

Inline-block:

![screen shot 2015-08-18 at 16 35 34](https://cloud.githubusercontent.com/assets/713293/9334523/2ec52124-45c7-11e5-95cb-9583f4c5bdfb.png)

**Comment by argyleink** [comment]
that's it! works great =)

![](http://media.giphy.com/media/lFlZd7ZmoUqVa/giphy.gif)

**Comment by argyleink** [comment]
after double checking, i think we need to expand this feature! right now, `grid__col-auto` operates like the other non-collapsable columns like `grid__col-3`, but it would behoove the grid to have a "liquid responsive" layout system, and it could be as easy as supporting the following naming convention: 

`grid__col-xs`
`grid__col-sm`
`grid__col-md`
`grid__col-lg`

auto width at each sizes respective viewports, the lack of a number (col-3, col-2, etc) to indicate column width means it's auto. if you find this naming convention viable, we may consider changing the non-collapsable column name to `grid__col` to be consistent.

this would let me make a responsive liquid grid with auto widths. and just like with `grid__col-auto` there is no good inline-block fallback, so the grid would rag right for inline-block. it would be on the dev to write some js to resolve that.

**Comment by leejordan** [comment]
implemented in release 1.0.3
