### ISSUE TITLE
Add flag to remove fallback for legacy browsers without flex support

### ISSUE THREAD

**Issue by dfedynich** [leejordan/reflex#40]
Hey, guys! Your fallback for older browsers that do not support flexbox is reliable. But this fallback make you include many redundant properties even we use reflex in the scope of modern browsers only. Using _word-spacing_ and _letter-spacing_ properties is great workaround to handle spaces between inline-block elements indeed. But these properties and many other make reflex solution overwhelmed in flexbox context. What about to provide sass (less) variable to handle legacy browsers? It will be make the final css smaller and more robust. What do you think?

**Comment by leejordan** [comment]
This is a great suggestion. This originally started solely as a way to use flexbox with a fallback, but that fallback is becoming increasingly less and less relevant as browsers mature.

**Comment by leejordan** [comment]
I've added this functionality in release 1.4.0. Thanks for the suggestion!

https://github.com/leejordan/reflex/releases/tag/1.4.0
