### ISSUE TITLE
Possible to release non-breaking BEM-supported 2.0?

### ISSUE THREAD

**Issue by leslc** [leejordan/reflex#48]
Hi @leejordan,

Thanks for sharing the reflex grid.  Our project has benefited immensely from it.  We want to upgrade to 2.0 but there are too many pages to regression to change the HTML.

I know you have thought over the BEM naming issue a bit.  As some people have requested backward compatible version as well, would you entertain publishing an older version (e.g. v1.9) that has your 2.0 improvements with old BEM naming?

I understand that "support" isn't necessarily what you're doing this for. :)  I'd be happy to work on this (with a few pointers, e.g. is "_grid.scss" the only place to change the naming of "col" --> "grid__col"?)

Thanks!

**Comment by miketdonahue** [comment]
My project would also be interested in backward compatibility if possible 👍

**Comment by leejordan** [comment]
I'm not sure if I can spare the time to do this but it certainly is possible to find/replace all the class names then build your own version.
