### ISSUE TITLE
nested grid within a col* without extra .grid element?

### ISSUE THREAD

**Issue by leeoniya** [leejordan/reflex#50]
hey @leejordan 

is it possible to create a nested grid by simply adding .grid class to an existing .col* element and continue nesting more .col* directly within it?

i tried it with the nested example on the demo page but it didnt quite work.

thanks!

**Comment by marcorieser** [comment]
With the approach used here it doesn‘t seem possible to me.

**Comment by leejordan** [comment]
Sorry but this won't work. The hierarchy of elements is quite strict.
