### ISSUE TITLE
Ordering of css classes destroyes font spacing

### ISSUE THREAD

**Issue by sense-design** [leejordan/reflex#56]
Example: `class="block col-sm-12"`

destroys my fonts within grid because on `.col-` the `^` is used and not `*`

When switching the class to `class="col-sm-12 block"` everything looks good but within CMS you sometimes have no direct possibility to change the class order.

**Comment by leejordan** [comment]
I think this is a fair comment. I'm wondering now if there are any downsides to using the * wildcard.

**Comment by marcorieser** [comment]
I think there should be no dowside to the wildcard. Possible fix could also be to generate each class for its own like bootstrap does it. Either way it should work in every position the class is set in html.

**Comment by leejordan** [comment]
I suspect it performs much worse as a selector but I think this is a real problem that needs solving (even though it hasn't affected me yet)

**Comment by leejordan** [comment]
This is now fixed in the latest release
