### ISSUE TITLE
Use Reflex Grid as a responsive table replacement

### ISSUE THREAD

**Issue by dev4press** [leejordan/reflex#58]
Is it possible to use Reflex as a replacement for TABLE, so that colums are properly wrapped, and cells rearanged for responsive layout? Is there an example fir this available somewhere?

**Comment by leejordan** [comment]
I'm not 100% sure I understand your requirement. Can you show me an example or maybe a mockup?

**Comment by dev4press** [comment]
Classic HTML TABLE:

```
<table>
  <thead></thead>
  <tbody>
    <tr>
       <th>...</th>
       <td>...</td>
    </tr>
  </tbody>
  <tfoot></tfoot>
</table>
```

**Comment by leejordan** [comment]
I can't really visualize how you would want the cells rearranged for responsive layout sorry

**Comment by dev4press** [comment]
Each row has a number of cells, and for one row Reflex works fine, it is responsive. If I have 2 rows, they behave independently with Reflex, and each row has cells with different sizes. It only needs to keep the same layout, same cell size, just like table does for each row. Can Reflex 'sync' cell sizes for all rows in the same wrapper?

**Comment by iKova82** [comment]
I think he want a fallback for wrapped items in older browsers with display:table; and display:table-cells;
This is what i also searching for.

**Comment by leejordan** [comment]
I'm not really sure if this will work with this grid. Unless anybody wants to experiment with it I'm not sure how to answer right now.
