### ISSUE TITLE
Still maintaining this project?

### ISSUE THREAD

**Issue by ghost** [leejordan/reflex#63]
Hi LeeJordan,
you still maintaining this project?
Greetings and thanks for this great work.

**Comment by leejordan** [comment]
I consider it to be pretty much feature complete but if there's a bug or issue I would be interested.

This project was really useful to me to bridge the gap as browsers adopted flexbox, but flexbox coverage is pretty complete now, so I expect usage of this project to decline except where people are forced to support older browsers for whatever reason. I'm finding that happens less and less now personally.

**Comment by ghost** [comment]
Hi LeeJordan,
it was only a question. Yes it is very complete, no bugs and as i told " Great Work". I like it.

**Comment by idenisovs** [comment]
Hi @leejordan! I would also like to say thank you for this great job!

**Comment by leejordan** [comment]
Thanks very much :+1:
