### ISSUE TITLE
Slash for divisions in SCSS will be deprecated

### ISSUE THREAD

**Issue by jeroen-slagt** [leejordan/reflex#68]
Hi,

reflex-grid/scss/includes/_mixins.scss  
uses a slash for division calculations.
percentage(($index / $reflex-columns))

This will be deprecated in SCSS in the future
Please use: math.div($index, $reflex-columns)

See: https://sass-lang.com/documentation/breaking-changes/slash-div

**Comment by questionmark78** [comment]
calc($index / $reflex-columns) will also work, which makes it perhaps a bit more readable code.

**Comment by chrisrosner** [comment]
@leejordan If I submit a pull request to fix this, would it be accepted?

**Comment by leejordan** [comment]
Yes for sure. I don't write code much these days but I would make a new
release of this.
